# Generated by Django 4.2.14 on 2024-10-08 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_product_category_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.category'),
        ),
    ]
